name: Build

on:
  push:
    branches: [ "3.0_Features" ]
    tags:
      - '*'
  pull_request:
    branches: [ "3.0_Features" ]

env:
  CSPROJ: "./BloonsTD6 Mod Helper/BloonsTD6 Mod Helper.csproj"
  MELONLOADER_ARTIFACT: MelonLoader.x64.CI.Release
  BLOONSTD6: ./BloonsTD6

jobs:
  build:
    
    runs-on: windows-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@master
        
      - name: Download MelonLoader
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          run_id: 2646562782
          name: ${{ env.MELONLOADER_ARTIFACT }}
          repo: LavaGang/MelonLoader
          path: ${{ env.BLOONSTD6 }}
  
      - name: Clone Dependencies Repo
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: doombubbles/btd6-ci-dependencies
          ref: main
          path: ${{ env.BLOONSTD6 }}/MelonLoader/Managed

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x # net6 can still build older as well

      - name: Build
        run: dotnet build -c BTD6_Release "${{ env.CSPROJ }}" -p:BloonsTD6="../BloonsTD6"

      - name: Upload Mod DLL
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: Mod DLL
          # A file, directory or wildcard pattern that describes what to upload
          path: ./Output/BtdModHelper.dll
      
      - name: Upload Mod Documentation
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: Mod Documentation
          # A file, directory or wildcard pattern that describes what to upload
          path: ./Output/BtdModHelper.xml